<?php

namespace App\DataFixtures;

use App\Entity\Book;
use App\Entity\Category;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class BookFixtures extends Fixture implements DependentFixtureInterface
{

    const BOOK_REFERENCE_1 = 'book-etranger';
    const BOOK_REFERENCE_2 = 'book-petit-prince';

    public function load(ObjectManager $manager): void
    {
        $books = [
            [
                'title' => "L'Étranger",
                'author' => 'Albert Camus',
                'isbn' => '9782070360024',
                'description' => "Un roman bref et marquant autour de Meursault, de l'absurde et du jugement social.",
                'publishedAt' => '1942-01-01',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_ROMAN,
            ],
            [
                'title' => 'Le Petit Prince',
                'author' => 'Antoine de Saint-Exupéry',
                'isbn' => '9782070612758',
                'description' => "Un conte poétique sur l'enfance, l'amitié et le regard que l'on porte sur le monde.",
                'publishedAt' => '1943-01-01',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'category' => CategoryFixtures::CATEGORY_JEUNESSE,
            ],
            [
                'title' => 'Germinal',
                'author' => 'Émile Zola',
                'isbn' => '9782253004226',
                'description' => "Une fresque sociale sur la condition ouvrière et la révolte des mineurs.",
                'publishedAt' => '1885-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Les Misérables',
                'author' => 'Victor Hugo',
                'isbn' => '9782253096337',
                'description' => "Le parcours de Jean Valjean dans une France traversée par la misère, la justice et la rédemption.",
                'publishedAt' => '1862-01-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'La Peste',
                'author' => 'Albert Camus',
                'isbn' => '9782070360420',
                'description' => "Le récit d'une ville frappée par une épidémie et des choix humains qu'elle révèle.",
                'publishedAt' => '1947-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_ROMAN,
            ],
            [
                'title' => 'Madame Bovary',
                'author' => 'Gustave Flaubert',
                'isbn' => '9782253004868',
                'description' => "Le portrait d'Emma Bovary, prise entre ses rêves romanesques et la réalité provinciale.",
                'publishedAt' => '1857-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Notre-Dame de Paris',
                'author' => 'Victor Hugo',
                'isbn' => '9782253009689',
                'description' => "Un grand roman historique autour de la cathédrale, de Quasimodo, d'Esmeralda et du Paris médiéval.",
                'publishedAt' => '1831-01-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_HISTORIQUE,
            ],
            [
                'title' => 'Bel-Ami',
                'author' => 'Guy de Maupassant',
                'isbn' => '9782253009009',
                'description' => "L'ascension de Georges Duroy dans le Paris mondain et journalistique du XIXe siècle.",
                'publishedAt' => '1885-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Le Père Goriot',
                'author' => 'Honoré de Balzac',
                'isbn' => '9782253085799',
                'description' => "Un roman central de La Comédie humaine, entre ambition sociale, argent et amour paternel.",
                'publishedAt' => '1835-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Vingt mille lieues sous les mers',
                'author' => 'Jules Verne',
                'isbn' => '9782253006329',
                'description' => "Une aventure sous-marine avec le professeur Aronnax et le capitaine Nemo à bord du Nautilus.",
                'publishedAt' => '1870-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_AVENTURE,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'isbn' => '9780451524935',
                'description' => "Un roman d'anticipation sur la surveillance, le pouvoir et la manipulation du langage.",
                'publishedAt' => '1949-06-08',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_SCIFI,
            ],
            [
                'title' => 'La Ferme des animaux',
                'author' => 'George Orwell',
                'isbn' => '9780451526342',
                'description' => "Une fable politique sur la prise de pouvoir, la propagande et la trahison des ideaux.",
                'publishedAt' => '1945-08-17',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_POLITIQUE,
            ],
            [
                'title' => 'Fahrenheit 451',
                'author' => 'Ray Bradbury',
                'isbn' => '9780345250273',
                'description' => "Un futur ou les livres sont interdits et ou lire devient un acte de resistance.",
                'publishedAt' => '1953-10-19',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_SCIFI,
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'isbn' => '9780441172719',
                'description' => "Une epopee de science-fiction entre desert, politique, religion et destin.",
                'publishedAt' => '1965-08-01',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'category' => CategoryFixtures::CATEGORY_SCIFI,
            ],
            [
                'title' => 'Fondation',
                'author' => 'Isaac Asimov',
                'isbn' => '9780553293357',
                'description' => "La chute d'un empire galactique et le pari d'une science capable d'en reduire le chaos.",
                'publishedAt' => '1951-01-01',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_SCIFI,
            ],
            [
                'title' => 'Le Hobbit',
                'author' => 'J. R. R. Tolkien',
                'isbn' => '9780547928227',
                'description' => "Le voyage initiatique de Bilbo au coeur d'un monde peuple de dragons et de tresors.",
                'publishedAt' => '1937-09-21',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_FANTASTIQUE,
            ],
            [
                'title' => 'Le Seigneur des anneaux',
                'author' => 'J. R. R. Tolkien',
                'isbn' => '9780544003415',
                'description' => "Une quete epique contre les forces de Sauron dans la Terre du Milieu.",
                'publishedAt' => '1954-07-29',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'category' => CategoryFixtures::CATEGORY_FANTASTIQUE,
            ],
            [
                'title' => 'Harry Potter a l\'ecole des sorciers',
                'author' => 'J. K. Rowling',
                'isbn' => '9780747532699',
                'description' => "L'entree d'un jeune sorcier dans un univers d'ecole, de magie et de mysteres.",
                'publishedAt' => '1997-06-26',
                'totalCopies' => 7,
                'availableCopies' => 7,
                'category' => CategoryFixtures::CATEGORY_JEUNESSE,
            ],
            [
                'title' => 'Le Nom de la rose',
                'author' => 'Umberto Eco',
                'isbn' => '9780156001311',
                'description' => "Une enquete erudite dans une abbaye medievale entre meurtres et savoir interdit.",
                'publishedAt' => '1980-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_POLICIER,
            ],
            [
                'title' => 'Da Vinci Code',
                'author' => 'Dan Brown',
                'isbn' => '9780307474278',
                'description' => "Un thriller fonde sur une course contre la montre et des enigmes historiques.",
                'publishedAt' => '2003-03-18',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_POLICIER,
            ],
            [
                'title' => 'Une etude en rouge',
                'author' => 'Arthur Conan Doyle',
                'isbn' => '9780486474915',
                'description' => "La premiere enquete de Sherlock Holmes et du docteur Watson.",
                'publishedAt' => '1887-11-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_POLICIER,
            ],
            [
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'isbn' => '9780486411095',
                'description' => "Un classique gothique autour du vampire le plus celebre de la litterature.",
                'publishedAt' => '1897-05-26',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_HORREUR,
            ],
            [
                'title' => 'Frankenstein',
                'author' => 'Mary Shelley',
                'isbn' => '9780486282114',
                'description' => "Une reflexion romanesque sur la creation, la science et la responsabilite.",
                'publishedAt' => '1818-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_HORREUR,
            ],
            [
                'title' => 'Ca',
                'author' => 'Stephen King',
                'isbn' => '9781501142970',
                'description' => "Un roman d'horreur sur l'enfance, la peur et un mal ancien.",
                'publishedAt' => '1986-09-15',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_HORREUR,
            ],
            [
                'title' => 'Shining',
                'author' => 'Stephen King',
                'isbn' => '9780307743657',
                'description' => "L'isolement d'un hotel enneige devient le theatre d'une lente descente dans la folie.",
                'publishedAt' => '1977-01-28',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_HORREUR,
            ],
            [
                'title' => 'Orgueil et Prejuges',
                'author' => 'Jane Austen',
                'isbn' => '9780141439518',
                'description' => "Une comedie de moeurs sur l'orgueil, les apparences et les alliances sociales.",
                'publishedAt' => '1813-01-28',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Jane Eyre',
                'author' => 'Charlotte Bronte',
                'isbn' => '9780142437209',
                'description' => "Le destin d'une heroine independante entre passion, morale et secret.",
                'publishedAt' => '1847-10-16',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Les Hauts de Hurlevent',
                'author' => 'Emily Bronte',
                'isbn' => '9780141439556',
                'description' => "Une histoire d'amour sombre et de vengeance sur les landes anglaises.",
                'publishedAt' => '1847-12-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Moby Dick',
                'author' => 'Herman Melville',
                'isbn' => '9780142437247',
                'description' => "La poursuite obsessionnelle d'une baleine blanche devient une meditation sur l'absolu.",
                'publishedAt' => '1851-10-18',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_AVENTURE,
            ],
            [
                'title' => 'L\'Ile au tresor',
                'author' => 'Robert Louis Stevenson',
                'isbn' => '9780141321004',
                'description' => "Une chasse au tresor qui a fixe l'imaginaire moderne des pirates.",
                'publishedAt' => '1883-11-14',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_AVENTURE,
            ],
            [
                'title' => 'Les Trois Mousquetaires',
                'author' => 'Alexandre Dumas',
                'isbn' => '9780143105008',
                'description' => "Une aventure de cape et d'epee portee par l'amitie, l'audace et l'honneur.",
                'publishedAt' => '1844-01-01',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_AVENTURE,
            ],
            [
                'title' => 'Le Comte de Monte-Cristo',
                'author' => 'Alexandre Dumas',
                'isbn' => '9780140449266',
                'description' => "Un grand recit de trahison, de patience et de vengeance.",
                'publishedAt' => '1844-08-28',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_HISTORIQUE,
            ],
            [
                'title' => 'Guerre et Paix',
                'author' => 'Leo Tolstoy',
                'isbn' => '9781400079988',
                'description' => "Une fresque historique et familiale dans la Russie des guerres napoleoniennes.",
                'publishedAt' => '1869-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_HISTORIQUE,
            ],
            [
                'title' => 'Crime et Chatiment',
                'author' => 'Fyodor Dostoevsky',
                'isbn' => '9780140449136',
                'description' => "Le drame moral d'un etudiant confronte a la culpabilite et a ses propres theories.",
                'publishedAt' => '1866-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CLASSIQUE,
            ],
            [
                'title' => 'Les Freres Karamazov',
                'author' => 'Fyodor Dostoevsky',
                'isbn' => '9780374528379',
                'description' => "Un roman foisonnant sur la foi, le doute, la famille et la responsabilite.",
                'publishedAt' => '1880-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_PHILOSOPHIE,
            ],
            [
                'title' => 'Pensees pour moi-meme',
                'author' => 'Marcus Aurelius',
                'isbn' => '9780812968255',
                'description' => "Des pensees stoiciennes sur la conduite de soi et le rapport au monde.",
                'publishedAt' => '0180-01-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_PHILOSOPHIE,
            ],
            [
                'title' => 'La Republique',
                'author' => 'Plato',
                'isbn' => '9780872201361',
                'description' => "Un dialogue majeur sur la justice, la cite ideale et l'education.",
                'publishedAt' => '0380-01-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_PHILOSOPHIE,
            ],
            [
                'title' => 'L\'Art de la guerre',
                'author' => 'Sun Tzu',
                'isbn' => '9781599869773',
                'description' => "Un traite bref et influent sur la strategie, le conflit et la decision.",
                'publishedAt' => '0500-01-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_ESSAI,
            ],
            [
                'title' => 'Sapiens',
                'author' => 'Yuval Noah Harari',
                'isbn' => '9780062316097',
                'description' => "Une synthese accessible sur l'histoire longue de l'humanite.",
                'publishedAt' => '2011-01-01',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_SCIENCE,
            ],
            [
                'title' => 'Une breve histoire du temps',
                'author' => 'Stephen Hawking',
                'isbn' => '9780553380163',
                'description' => "Une introduction celebre aux grandes questions de la cosmologie moderne.",
                'publishedAt' => '1988-04-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_SCIENCE,
            ],
            [
                'title' => 'Le Gene egoiste',
                'author' => 'Richard Dawkins',
                'isbn' => '9780199291151',
                'description' => "Un essai marquant sur l'evolution et la selection naturelle vue par le gene.",
                'publishedAt' => '1976-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_SCIENCE,
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'isbn' => '9780132350884',
                'description' => "Des principes concrets pour ecrire un code plus lisible, testable et durable.",
                'publishedAt' => '2008-08-01',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_DEV,
            ],
            [
                'title' => 'Refactoring',
                'author' => 'Martin Fowler',
                'isbn' => '9780201485677',
                'description' => "Une methode progressive pour ameliorer la structure interne d'un logiciel.",
                'publishedAt' => '1999-07-08',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_DEV,
            ],
            [
                'title' => 'Design Patterns',
                'author' => 'Erich Gamma',
                'isbn' => '9780201633610',
                'description' => "Un repertoire de solutions classiques aux problemes de conception logicielle.",
                'publishedAt' => '1994-10-21',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_TECHNOLOGIE,
            ],
            [
                'title' => 'Le Programmeur pragmatique',
                'author' => 'Andrew Hunt',
                'isbn' => '9780201616224',
                'description' => "Un guide de pratique professionnelle pour les developpeurs et les equipes.",
                'publishedAt' => '1999-10-30',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'category' => CategoryFixtures::CATEGORY_DEV,
            ],
            [
                'title' => 'Deep Work',
                'author' => 'Cal Newport',
                'isbn' => '9781455586691',
                'description' => "Une reflexion sur la concentration, la qualite du travail et la maitrise de l'attention.",
                'publishedAt' => '2016-01-05',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_DEVELOPPEMENT_PERSONNEL,
            ],
            [
                'title' => 'Un rien peut tout changer',
                'author' => 'James Clear',
                'isbn' => '9780735211292',
                'description' => "Des leviers simples pour faire evoluer durablement ses comportements quotidiens.",
                'publishedAt' => '2018-10-16',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'category' => CategoryFixtures::CATEGORY_DEVELOPPEMENT_PERSONNEL,
            ],
            [
                'title' => 'Systeme 1 / Systeme 2',
                'author' => 'Daniel Kahneman',
                'isbn' => '9780374533557',
                'description' => "Une exploration des biais cognitifs et des deux grands modes de pensee.",
                'publishedAt' => '2011-10-25',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_PSYCHOLOGIE,
            ],
            [
                'title' => 'Decouvrir un sens a sa vie',
                'author' => 'Viktor E. Frankl',
                'isbn' => '9780807014295',
                'description' => "Un temoignage et une meditation sur le sens, la souffrance et la resilience.",
                'publishedAt' => '1946-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_PSYCHOLOGIE,
            ],
            [
                'title' => 'Les 7 habitudes de ceux qui realisent tout ce qu\'ils entreprennent',
                'author' => 'Stephen R. Covey',
                'isbn' => '9780743269513',
                'description' => "Un classique du developpement personnel centre sur les habitudes et les principes.",
                'publishedAt' => '1989-08-15',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_DEVELOPPEMENT_PERSONNEL,
            ],
            [
                'title' => 'Steve Jobs',
                'author' => 'Walter Isaacson',
                'isbn' => '9781451648539',
                'description' => "Une biographie detaillee d'un entrepreneur majeur de l'industrie technologique.",
                'publishedAt' => '2011-10-24',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_BIOGRAPHIE,
            ],
            [
                'title' => 'Un long chemin vers la liberte',
                'author' => 'Nelson Mandela',
                'isbn' => '9780316548182',
                'description' => "Le recit d'une vie de lutte politique, de prison et de reconciliation.",
                'publishedAt' => '1994-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_AUTOBIOGRAPHIE,
            ],
            [
                'title' => 'Le Journal d\'Anne Frank',
                'author' => 'Anne Frank',
                'isbn' => '9780553296983',
                'description' => "Le journal devenu universel d'une adolescente cachee pendant la guerre.",
                'publishedAt' => '1947-06-25',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_AUTOBIOGRAPHIE,
            ],
            [
                'title' => 'Le Manifeste du parti communiste',
                'author' => 'Karl Marx',
                'isbn' => '9780140447576',
                'description' => "Un texte politique bref sur les classes sociales, le capital et la revolution.",
                'publishedAt' => '1848-02-21',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_POLITIQUE,
            ],
            [
                'title' => 'La Richesse des nations',
                'author' => 'Adam Smith',
                'isbn' => '9780553585971',
                'description' => "Un ouvrage fondateur de l'economie politique moderne.",
                'publishedAt' => '1776-03-09',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_ECONOMIE,
            ],
            [
                'title' => 'L\'Investisseur intelligent',
                'author' => 'Benjamin Graham',
                'isbn' => '9780060555665',
                'description' => "Un classique de l'investissement prudent et de la discipline financiere.",
                'publishedAt' => '1949-01-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_FINANCE,
            ],
            [
                'title' => 'Pere riche, pere pauvre',
                'author' => 'Robert T. Kiyosaki',
                'isbn' => '9781612681139',
                'description' => "Un livre populaire sur l'education financiere, les actifs et les revenus.",
                'publishedAt' => '1997-04-01',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_FINANCE,
            ],
            [
                'title' => 'Le Livre du Hygge',
                'author' => 'Meik Wiking',
                'isbn' => '9780062658807',
                'description' => "Une approche du bien-etre quotidien inspiree d'un art de vivre danois.",
                'publishedAt' => '2016-09-01',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'category' => CategoryFixtures::CATEGORY_SANTE,
            ],
            [
                'title' => 'Sel, gras, acide, chaleur',
                'author' => 'Samin Nosrat',
                'isbn' => '9781476753836',
                'description' => "Un livre de cuisine qui explique les grands principes avant les recettes.",
                'publishedAt' => '2017-04-25',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_CUISINE,
            ],
            [
                'title' => 'Sur la route',
                'author' => 'Jack Kerouac',
                'isbn' => '9780142437254',
                'description' => "Un roman de mouvement, de jeunesse et de voyage a travers les Etats-Unis.",
                'publishedAt' => '1957-09-05',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'category' => CategoryFixtures::CATEGORY_VOYAGE,
            ],
        ];

        foreach ($books as $bookData) {
            $book = new Book();
            $book->setTitle($bookData['title']);
            $book->setAuthor($bookData['author']);
            $book->setIsbn($bookData['isbn']);
            $book->setDescription($bookData['description']);
            $book->setPublishedAt(new \DateTimeImmutable($bookData['publishedAt']));
            $book->setTotalCopies($bookData['totalCopies']);
            $book->setAvailableCopies($bookData['availableCopies']);
            $book->setImage($this->getCoverUrl($bookData['isbn']));

            /** @var Category $category */
            $category = $this->getReference($bookData['category'], Category::class);
            $book->setCategory($category);

            $manager->persist($book);

            if ($bookData['isbn'] === '9782070360024') {
                $this->addReference(self::BOOK_REFERENCE_1, $book);
            }
            if ($bookData['isbn'] === '9782070612758') {
                $this->addReference(self::BOOK_REFERENCE_2, $book);
            }
        }

        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            CategoryFixtures::class,
        ];
    }

    private function getCoverUrl(string $isbn): string
    {
        return 'https://covers.openlibrary.org/b/isbn/' . $isbn . '-L.jpg?default=false';
    }
}
